// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjE5CBa0m5RgM5fhsdU57Njpfs0EbrDM',
    appId: '1:560867969316:web:0d2511d9e0183f709ccbb1',
    messagingSenderId: '560867969316',
    projectId: 'barcode47-46578',
    authDomain: 'barcode47-46578.firebaseapp.com',
    storageBucket: 'barcode47-46578.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_brx7BmIKEfgRdAzUuBI47MC2c1rij2g',
    appId: '1:560867969316:android:a83bcadecbb3779f9ccbb1',
    messagingSenderId: '560867969316',
    projectId: 'barcode47-46578',
    storageBucket: 'barcode47-46578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnTcoyW6WdD66z-u91Wmw4TvdSemAN7zM',
    appId: '1:560867969316:ios:a8aa3fd8483a1d019ccbb1',
    messagingSenderId: '560867969316',
    projectId: 'barcode47-46578',
    storageBucket: 'barcode47-46578.firebasestorage.app',
    iosBundleId: 'com.fox.barcode47',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnTcoyW6WdD66z-u91Wmw4TvdSemAN7zM',
    appId: '1:560867969316:ios:f5709c6f0959143b9ccbb1',
    messagingSenderId: '560867969316',
    projectId: 'barcode47-46578',
    storageBucket: 'barcode47-46578.firebasestorage.app',
    iosBundleId: 'com.fox.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhjE5CBa0m5RgM5fhsdU57Njpfs0EbrDM',
    appId: '1:560867969316:web:9fc70f9cc095af1e9ccbb1',
    messagingSenderId: '560867969316',
    projectId: 'barcode47-46578',
    authDomain: 'barcode47-46578.firebaseapp.com',
    storageBucket: 'barcode47-46578.firebasestorage.app',
  );
}
